### ISSUE TITLE
[Request] Compatibility with Mineral Tracker

### ISSUE THREAD

**Issue by angelnc1989** [YakosWG/PortableDrill#2]
https://www.curseforge.com/minecraft/mc-mods/mineral-tracker

It would be great if the Portable Drill would automatically add the Mineral-Mix and Fluid Reservoir to the Mineral Tracker map.

**Comment by YakoSWG** [comment]
Mineral Tracker's code seems to not be publicly available anywhere. I've contacted the dev (LordFokas) about it but it seems unlikely that I will be able to add integration for it.

**Comment by angelnc1989** [comment]
Thanks for your effort anyway =)

**Comment by YakoSWG** [comment]
I've added a config option to allow the drill to generate core samples instead of chat messages. This will allow you to automatically add the mineral deposits to Mineral Tracker. I'll still need to do some bug fixing but I might be able to release a beta version later today.

**Comment by angelnc1989** [comment]
Works great. Thanks mate!
